apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-svc-depl
  labels:
    service: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nats
  template:
    metadata:
      name: nats
      labels:
        service: casdoor
    spec:
      containers:
      - name: nats
        image: nats:2.9.18-alpine3.18
        ports:
        - containerPort: 4222